image: Previous Visual Studio 2017

build_script:
  - cmd: cd PNGDecrushTests
  - cmd: dotnet test
  - cmd: cd ..\PNGDecrush
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release
  - ps: Push-AppveyorArtifact "bin\Release\PNGDecrush.*.nupkg"
